const INVALID_DATA_ERROR = 400;

const NOTFOUND_ERROR = 404;

const DEFAULT_ERROR = 500;

const UNAUTHORIZED_ERROR = 401;


module.exports = {
  INVALID_DATA_ERROR,
  NOTFOUND_ERROR,
  DEFAULT_ERROR,
  UNAUTHORIZED_ERROR 
};